### PR TITLE
Downloads extensions and FAQs completed, also added a className of 'h…

### PR DESCRIPTION
**Pull request by DeewhyCodes**
…ome' to the home file

### CODE REVIEW

**Review by ezekieloyedijo — CHANGES_REQUESTED** [review]
1. Excellent work. 
Brilliant use of props and good organization of application data.
Would be cool if we can reduce the number of folders in downloadFaqs to one. Every component can be inside the downloadFaqs folder.

2. Can we add a transition on the accordion answer?

**Review by ezekieloyedijo — APPROVED** [review]
What a good initiative to make the necessary corrections promptly.
You have my approval👍

**Review by Andak-Creates — APPROVED** [review]
Wowww grape, This is peak

**Review by Techgnius — APPROVED** [review]
Good work Mr Vicky, the code is easy to follow.

**Pull request merged**
